title: Ical Bakhri Blog
email: email@domain.com
description: >- # Ganti dengan deskripsi blog Anda
  Blog personal yang membahas teknologi, pemrograman, dan kehidupan.
baseurl: ""
url: "https://icalbakhri.github.io" 
twitter:
  username: icalbakhri # Ganti jika ada

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Plugin SEO otomatis
