title: log.ical
description_en: "Notes on Linux, Server, Docker, Self-hosting, and web technology from Ical Bakhri's perspective."
description_id: "Catatan seputar Linux, Server, Docker, Self-hosting, dan teknologi web dari sudut pandang Ical Bakhri."
url: "https://log.ical.web.id"
baseurl: ""

author:
  name: "Ical Bakhri"
  email: "contact@log.ical.web.id" # Email Gravatar Anda
  github: "icalbakhri"
  linkedin: "icalbakhri"
  twitter: "icalbakhri"

timezone: "Asia/Jakarta"

plugins:
  - jekyll-seo-tag